version: "3.8"
 
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
 
  spark:
    image: bitnami/spark:latest
    container_name: spark
    ports:
      - "8080:8080"  # UI de Spark
      - "7077:7077"  # Puerto para conectar workers
    volumes:
      - ./spark-config:/opt/bitnami/spark/conf
    environment:
      SPARK_MODE: master
 
  databricks:
    build: .
    container_name: databricks
    ports:
      - "8888:8888"  # Puerto de Databricks Notebook
    depends_on:
      - spark
      - minio
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
 
volumes:
  minio_data: