name: mi_proyecto_dbt
version: '1.0'
config-version: 2

profile: mi_perfil

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_modules"

# Configuración por defecto para los modelos dentro del proyecto
models:
  mi_proyecto_dbt:
    +materialized: view  # Puedes cambiar a 'table' u otra configuración
